### ISSUE TITLE
KeyError: 'hero_id' - Probably not critical.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/RPG-Game#247]
This error can be create by:

1. Sending a POST request from the Client
2. having the JS code fail and 
3. then trying to View Page Source.

```
127.0.0.1 - - [17/Dec/2017 15:59:29] "POST /inbox/outbox HTTP/1.1" 200 -
Please document this as it is a hard to find bug.
127.0.0.1 - - [17/Dec/2017 15:59:36] "GET /inbox/outbox HTTP/1.1" 500 -
Traceback (most recent call last):
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1997, in __call__
	return self.wsgi_app(environ, start_response)
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1985, in wsgi_app
	response = self.handle_exception(e)
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
    File "C:\Program Files\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
	raise value
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
	response = self.full_dispatch_request()
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
	reraise(exc_type, exc_value, tb)
    File "C:\Program Files\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
	raise value
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
	rv = self.dispatch_request()
    File "C:\Program Files\Python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
    File "D:\Dropbox\The Written Word\Programming\pythgrams\RPG-game\app.py", line 198, in wrap_uses_hero
        raise ex
    File "D:\Dropbox\The Written Word\Programming\pythgrams\RPG-game\app.py", line 194, in wrap_uses_hero
        hero = database.get_object_by_id("Hero", session["hero_id"])
    File "C:\Program Files\Python35\lib\site-packages\werkzeug\local.py", line 377, in <lambda>
        __getitem__ = lambda x, i: x._get_current_object()[i]
    KeyError: 'hero_id'
```

**Comment by klondikemarlen** [comment]
I 'fixed' it. Now if you view page source after a POST request ... opens a page telling you to "reload the page first". Kind of lame as it doesn't fix the problem but .. I am marking it as fixed for now.
